<a href="https://colab.research.google.com/github/SooMiiii/23-2-ESAA/blob/main/0908_hw_Numpy_exercises(26~39).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

In [1]:
import numpy as np

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [5]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

In [6]:
common_values = Z1[np.isin(Z1, Z2)]
print(common_values)

[7 5 5 9 5]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [10]:
# np.sqrt(-1) == np.emath.sqrt(-1)
# False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [12]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [15]:
A = np.random.random(3)
B = np.random.random(3)

result = np.empty_like(A)

np.add(A, B, out=result)
np.negative(A, out=result)
np.divide(result, 2, out=result)
np.multiply(result, -1, out=result)

print(result)

[0.26940337 0.15988253 0.33809324]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [24]:
a = np.random.uniform(0, 10, 10)
a - (a % 1 )

array([5., 2., 1., 9., 6., 4., 5., 9., 0., 0.])

In [25]:
a // 1

array([5., 2., 1., 9., 6., 4., 5., 9., 0., 0.])

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [27]:
a = np.random.uniform(0, 4, (5,5))
a

array([[2.56807618, 1.4218856 , 2.15955398, 1.43222715, 0.18496334],
       [2.9647864 , 3.54805223, 0.46882487, 0.59159755, 0.31409385],
       [3.13994276, 0.35496269, 0.26742014, 2.05546645, 1.7053715 ],
       [2.7458681 , 3.7775434 , 3.84755914, 0.29577996, 0.04165298],
       [0.90086438, 0.69821586, 2.76325303, 0.99860638, 2.24735649]])

#### 32. Create a random vector of size 10 and sort it (★★☆)

In [29]:
np.sort(np.random.rand(10))

array([0.24368916, 0.255573  , 0.31317406, 0.31562125, 0.32850294,
       0.35646825, 0.67802423, 0.68333335, 0.72964889, 0.81925154])

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [30]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A,B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [31]:
a = np.random.rand(10, 2)

x = a[:, 0]
y = a[:, 1]

distance = np.sqrt(x**2 + y**2)
angle = np.arctan2(y, x)

polar_coordinates = np.column_stack((distance, angle))

print(a)
print(polar_coordinates)

[[0.89021651 0.55559232]
 [0.44939458 0.32627899]
 [0.30028402 0.124982  ]
 [0.07445158 0.3435104 ]
 [0.51267216 0.22162162]
 [0.21714291 0.13388208]
 [0.67121217 0.97132846]
 [0.10000887 0.71019556]
 [0.7697776  0.17409464]
 [0.97898242 0.15109029]]
[[1.04936564 0.55795849]
 [0.55534986 0.62799034]
 [0.32525527 0.39440418]
 [0.35148603 1.35736005]
 [0.55852385 0.40802676]
 [0.25509891 0.55250855]
 [1.18067978 0.96611934]
 [0.71720256 1.43089744]
 [0.78921892 0.22242042]
 [0.990573   0.15312588]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [32]:
z = np.random.rand(10)
z[z.argmax()]=0
z

array([0.        , 0.05263716, 0.04304139, 0.00270519, 0.51141167,
       0.6336702 , 0.12768856, 0.18827729, 0.26657805, 0.15919145])

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [33]:
Z = np.random.rand(5)
v = 5
Z[np.abs(Z - v).argmin()]

0.7979431042231293

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [34]:
Z = np.arange(9).reshape(3, 3)

for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [35]:
n = 5
p = 7
value = 10

Z = np.zeros((n, n))
indices = np.random.choice(range(n * n), p, replace=False)
coordinates = np.unravel_index(indices, (n, n))
Z[coordinates] = value
Z

array([[ 0., 10.,  0.,  0., 10.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 10.,  0., 10.],
       [ 0., 10.,  0., 10.,  0.],
       [ 0., 10.,  0.,  0.,  0.]])

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [36]:
Z = np.random.randint(0, 10, (3, 3))

In [37]:
# column 1
Z[Z[:,0].argsort()]

array([[2, 2, 3],
       [5, 5, 4],
       [7, 5, 0]])

In [38]:
# column 2
Z[Z[:,1].argsort()]

array([[2, 2, 3],
       [5, 5, 4],
       [7, 5, 0]])

In [39]:
# column 3
Z[Z[:,2].argsort()]

array([[7, 5, 0],
       [2, 2, 3],
       [5, 5, 4]])